-- phpMyAdmin SQL Dump
-- version 4.7.1
-- https://www.phpmyadmin.net/
--
-- Host: 34.101.202.190
-- Generation Time: Jun 16, 2023 at 10:17 AM
-- Server version: 5.7.40-google-log
-- PHP Version: 7.0.33-0ubuntu0.16.04.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `hewan`
--

-- --------------------------------------------------------

--
-- Table structure for table `animal`
--

CREATE TABLE `animal` (
  `id_animal` int(5) NOT NULL,
  `nama_hewan` varchar(1000) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `nama` varchar(1000) NOT NULL,
  `jenis` varchar(1000) NOT NULL,
  `diet` varchar(1000) NOT NULL,
  `makanan` varchar(1000) NOT NULL,
  `reproduksi` varchar(1000) NOT NULL,
  `tubuh` varchar(1000) NOT NULL,
  `kemampuan` varchar(1000) NOT NULL,
  `habitat` varchar(1000) NOT NULL,
  `pernapasan` varchar(1000) NOT NULL,
  `pergerakan` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `animal`
--

INSERT INTO `animal` (`id_animal`, `nama_hewan`, `description`, `nama`, `jenis`, `diet`, `makanan`, `reproduksi`, `tubuh`, `kemampuan`, `habitat`, `pernapasan`, `pergerakan`) VALUES
(1, 'ant', 'Semut adalah serangga kecil yang hidup dalam koloni yang terorganisir yang bisa dijumpai di berbagai habitat. Mereka memiliki tubuh yang tersegmentasi dan enam kaki. Semut dikenal karena kerja sama mereka yang kuat dalam mencari makanan dan melindungi sarang mereka. Semut memakan banyak hal yang tersedia di sekitar mereka, mulai dari serangga mati, sayuran, buah-buahan, kayu atau daging yang telah membusuk hingga memakan semut lain.', 'Semut (Formicidae)', 'Insecta (serangga), hymenoptera (membran dan sayap)', 'Omnivora (pemakan segalanya)', 'Serangga mati, sayuran, buah-buahan, kayu atau daging yang telah membusuk hingga memakan semut lain', 'Ovipar (bertelur)', 'Tiga bagian utama, yaitu kepala, thoraks, dan perut', 'Bekerjasama dan kompak dalam mengangkut makanan', 'Berbagai habitat seperti hutan, pasir dan pohon di seluruh dunia', 'Trakea', 'Berjalan, memanjat'),
(2, 'bear', 'Beruang adalah mamalia besar yang biasanya ditemukan di daerah hutan Asia, Eropa, dan Amerika. Mereka memiliki cakar yang kuat, gigi taring yang besar, dan bulu yang tebal. Beruang cenderung omnivora, memakan buah-buahan, madu, ikan, dan daging mamalia kecil. Beruang melakukan hibernasi yaitu tidur siang yang panjang selama musim dingin dan bangun di musim semi.', 'Beruang (Ursidae)', 'Mamalia (menyusui)', 'Omnivora (pemakan segalanya)', 'Buah-buahan, madu, ikan, dan daging mamalia kecil', 'Vivipar (melahirkan)', 'Tubuh besar, cakar kuat, gigi taring yang besar tajam, dan bulu yang tebal', 'Kemampuan mendengar, memanjat pohon dan berenang yang baik, hibernasi yaitu tidur siang yang panjang selama musim dingin ', 'Hutan Asia, Eropa, dan Amerika', 'Paru-paru', 'Berjalan, berlari, memanjat, berenang'),
(3, 'bee', 'Lebah adalah serangga yang terkenal karena menghasilkan madu. Mereka memiliki tubuh berbulu dan dua pasang sayap. Lebah memainkan peran penting dalam penyerbukan tanaman dan juga membentuk koloni dengan tugas-tugas yang dibagi di dalamnya. Koloni lebah sendiri membuat sarangnya di pohon-pohon atau gua di berbagai lingkungan. Makanan lebah adalah nektar bunga yang dihasilkan oleh tanaman.', 'Lebah (Anthophila)', 'Insecta (serangga), hymenoptera (membran dan sayap)', 'Herbivora (pemakan tumbuhan)', 'Nektar (sari bunga) yang dihasilkan oleh tanaman', 'Ovipar (bertelur)', 'Tubuh yang terdiri dari kepala, thoraks, dan perut. Memiliki enam kaki, berbulu, dua pasang sayap dan sepasang antena', 'Terbang dari satu tempat ke tempat lain dengan kecepatan yang cukup tinggi, merasakan dan mengenali bau, getaran, dan arah dengan antenanya', 'Berbagai habitat di seluruh dunia termasuk hutan, padang rumput, taman, dan bahkan lingkungan perkotaan', 'Trakea', 'Berjalan, terbang'),
(4, 'beetle', 'Kumbang adalah serangga dengan tubuh keras yang biasanya dilengkapi dengan sayap. Ada banyak jenis kumbang dengan bentuk dan warna yang berbeda. Mereka memiliki peran penting dalam ekosistem sebagai pemakan sampah organik dan penyerbuk. Kumbang dapat ditemukan di semua habitat, kecuali di lautan dan wilayah kutub. Beberapa spesies kumbang memakan jamur dan memakan bunga atau buah.', 'Kumbang (Coleoptera)', 'Insecta (serangga), Coleoptera (perisai dan sayap)', 'Herbivora (pemakan tumbuhan)', 'Daun, buah, bunga, nektar, dan jamur', 'Ovipar (bertelur)', 'Tubuh keras yang biasanya dilengkapi dengan sayap', 'Beberapa spesies kumbang memiliki kemampuan terbang dengan sayap-sayap yang ada di bawah lapisan keras mereka', 'Semua habitat, kecuali di lautan dan wilayah kutub', 'Trakea', 'Berjalan, terbang'),
(5, 'buffalo', 'Kerbau adalah hewan bertubuh besar dengan tanduk melengkung yang panjang. Kerbau sering digunakan sebagai hewan tunggangan di beberapa negara. Kerbau dikenal karena kekuatan fisik dan daya tahannya. Habitat asli kerbau adalah di sekitar sungai dan makanannya adalah rerumputan.', 'Kerbau (Bubalus bubalis)', 'Mamalia (menyusui)', 'Herbivora (pemakan tumbuhan)', 'Rerumputan, dedaunan, batang pohon, dan tanaman air', 'Vivipar (melahirkan)', 'Tubuhnya besar dan berotot, memiliki leher yang pendek dan tebal, serta tanduk melengkung yang panjang', 'Kemampuan menarik beban yang berat sehingga sering dijadikan hewan tunggangan', 'Habitat asli di dataran rendah yang dekat dengan sumber air, seperti rawa-rawa, sungai, dan danau', 'Paru-paru', 'Berjalan dengan kecepatan yang rendah'),
(6, 'butterfly', 'Kupu-kupu adalah serangga yang memiliki sayap berwarna-warni cerah dan bentuk tubuh yang khas yang hidup di pohon. Tahap awal kehidupan mereka adalah sebagai ulat atau kepompong sebelum berubah menjadi kupu-kupu. Kupu-kupu merupakan penyerbuk yang penting dalam ekosistem. Kupu-kupu umumnya hidup dengan mengisap nectar atau sari bunga. Akan tetapi beberapa jenisnya menyukai cairan yang diisap dari buah-buahan yang jatuh di tanah. ', 'Kupu-Kupu (Rhopalocera)', 'Insecta (serangga), Lepidoptera (bersayap sisik)', 'Herbivora (pemakan tumbuhan)', 'Nektar (sari bunga) dan sari buah', 'Ovipar (bertelur)', 'Memiliki sayap, enam kaki dan tubuh yang terbagi menjadi tiga bagian, yaitu kepala, thorax, dan abdomen', 'Melakukan migrasi jarak jauh setiap tahunnya, membantu penyerbukan tanaman', 'Berbagai habitat termasuk hutan, taman, kebun, padang rumput, dan bahkan daerah perkotaan', 'Trakea', 'Terbang'),
(7, 'camel', 'Unta adalah hewan berkaki empat yang hidup di daerah gurun atau padang pasir di Asia. Mereka memiliki ciri khas yaitu leher dan bulu mata yang panjang, alis yang lebat, penutup hidung, dan memiliki satu atau dua punuk di punggungnya. Punuk yang dimiliki unta berfungsi untuk menyimpan lemak sebagai cadangan makanan, energi dan air sehingga mereka dapat bertahan dalam cuaca yang ekstrim. Unta sering digunakan sebagai hewan pengangkut sumber makanan dan material bagi manusia.', 'Unta (Camelus)', 'Mamalia (menyusui)', 'Herbivora (pemakan tumbuhan)', 'Berbagai tumbuhan gurun, seperti rumput, daun, cabang, dan bahkan kaktus', 'Vivipar (melahirkan)', 'Tubuh yang besar dan tinggi dengan kaki panjang, kuku besar, leher dan bulu mata panjang, alis lebat, penutup hidung, dan memiliki satu atau dua punuk di punggungnya', 'Menyimpan lemak sebagai cadangan makanan, energi dan air sehingga mereka dapat bertahan dalam cuaca yang ekstrim', 'Gurun atau padang pasir, Asia', 'Paru Paru', 'Berjalan'),
(8, 'cat', 'Kucing adalah hewan peliharaan yang populer. Mereka memiliki tubuh berukuran kecil hingga sedang, cakar yang tajam, dan bulu yang halus. Kucing adalah hewan yang mandiri, tetapi juga bisa menjadi teman yang menyenangkan. Habitat asli kucing ini sesuai dengan kemampuan berburunya seperti kucing-kucing besar dan liar yang hidup di sabana dan hutan. Makanan kucing sendiri adalah daging hewan yang juga beragam sesuai dengan habitatnya.', 'Kucing (Felis catus)', 'Mamalia (menyusui)', 'Karnivora (pemakan daging)', 'Daging hewan menyesuaikan habitatnya', 'Vivipar (melahirkan)', 'Tubuh yang lentur dengan ukuran bervariasi, cakar tajam, dan bulu halus', 'Pendengaran yang tajam, penglihatan malam yang baik, dan kemampuan melompat, memanjat, dan berlari dengan cepat tanpa mengeluarkan suara.', 'Habitat asli kucing di sabana dan hutan', 'Paru-Paru', 'Berjalan, berlari, memanjat'),
(9, 'caterpillar', 'Ulat adalah larva kupu-kupu yang memiliki badan Panjang, bulu yang lebat dan berwarna menarik. Ulat ini biasanya berwarna cerah sebagai peringatan bagi pemangsa potensial. Kebanyakan ulat dapat menyebabkan iritasi jika disentuh. Habitat ulat merupakan tempat-tempat yang lembab, di pepohonan atau tanaman hijau. Mereka bertahan hidup dengan memakan daun dan buah-buahan.', 'Ulat', 'Insecta (serangga)', 'Herbivora (pemakan tumbuhan)', 'Daun dan buah-buahan', 'Ovipar (bertelur)', 'Badan panjang, bulu yang lebat dan berwarna menarik', 'Bulu-bulu ini mengandung racun yang disebut setae yang dapat menyebabkan rasa gatal, iritasi, dan bahkan reaksi alergi pada kulit yang bersentuhan', 'Tempat-tempat yang lembab, di pepohonan atau tanaman hijau', 'Trakea', 'Merayap/merambat'),
(10, 'centipede', 'Lipan adalah serangga yang memiliki tubuh panjang dan banyak kaki. Mereka sering ditemukan di bawah bebatuan atau di daerah yang lembap. Kaki seribu memakan serangga kecil seperti cacing, laba-laba, dan semut, juga memakan buah busuk. Sebagian besar spesies lipan memiliki gigitan yang menyakitkan dan bisa mengandung racun.', 'Lipan (Chilopoda)', 'Insecta (serangga)', 'Omnivora (pemakan segalanya)', 'Serangga kecil seperti cacing, laba-laba, dan semut, juga memakan buah busuk', 'Ovipar (bertelur)', 'Tubuh panjang dan banyak kaki', 'Sebagian besar spesies lipan memiliki gigitan yang menyakitkan dan mengandung racun', 'Di bawah bebatuan atau di daerah yang lembab', 'Trakea', 'Merayap dengan cepat dan lincah'),
(11, 'chameleon', 'Bunglon adalah reptil yang memiliki kemampuan untuk mengubah warna kulit mereka sesuai dengan lingkungannya. Mereka memiliki lidah yang panjang dan lengket untuk menangkap mangsa. Bunglon sebagian besar hidup di hutan hujan dan gurun Afrika. Bunglon adalah reptil yang biasa memakan serangga seperti lalat, jangkrik, dan belalang', 'Bunglon (Bronchocela)', 'Reptil (melata)', 'Karnivora (pemakan daging)', 'Serangga seperti lalat, ulat, jangkrik, dan belalang', 'Ovipar (bertelur)', 'Tubuh panjang dan ramping dengan kepala menonjol serta mata yang bergerak secara independen, lidah yang panjang dan lengket', 'Mimikri, kemampuan untuk mengubah warna kulit mereka sesuai dengan lingkungannya', 'Berbagai habitat termasuk hutan, sabana, semak belukar, dan daerah yang dekat dengan air.', 'Paru-paru', 'Merayap'),
(12, 'cheetah', 'Cheetah adalah hewan pemangsa yang dikenal sebagai mamalia tercepat di darat. Mereka memiliki tubuh yang Panjang ramping, bulu yang tidak rata, alas kaki yang keras hingga tulang belakang fleksibel, dan ekor yang panjang untuk menjaga keseimbangan saat berlari dengan kecepatan tinggi. Cheetah terkenal dengan mantel kuning kecoklatannya yang ditutupi bintik-bintik hitam dengan garis-garis hitam tebal dari sudut dalam mata ke kedua sisi mulut mereka. Mereka bisa ditemukan di seluruh padang rumput di Asia dan Afrika. Cheetah memakan hewan berukuran kecil hingga sedang, seperti kelinci, zebra, dan rusa.', 'Citah (Acinonyx jubatus)', 'Mamalia (menyusui)', 'Karnivora (pemakan daging)', 'Kelinci, zebra, dan rusa', 'Vivipar (melahirkan)', 'Tubuh panjang, fleksibel dan ramping dengan ekor panjang dan kepala yang kecil.', 'Hewan darat tercepat di dunia dengan kecepatan ±97 km/jam', 'Padang rumput, sabana, dan gurun di Asia dan Afrika', 'Paru-paru', 'Berjalan, berlari'),
(13, 'chicken', 'Ayam adalah hewan unggas yang sering digunakan sebagai sumber daging dan telur. Mereka memiliki sayap yang kecil dan tidak dapat terbang jauh. Ayam biasanya hidup berkelompok dan memiliki berbagai jenis dengan ciri-ciri fisik yang berbeda. Habitat ayam adalah di daratan, seperti hutan, perkebunan, pekarangan rumah, dan kawasan pertanian. Makanan ayam adalah cacing, serangga dan biji-bijian seperti jagung juga padi.', 'Ayam (Gallus gallus domesticus)', 'Aves (burung)', 'Omnivora (pemakan segalanya', 'Cacing, serangga dan biji-bijian seperti jagung juga padi', 'Ovipar (bertelur)', 'Memiliki paruh pendek, sayap kecil, jengger, dan kaki bercakar', 'Kaki ayam jantan memiliki jalu lancip yang dapat digunakan untuk melukai musuhnya.', 'Habitat asli ayam di hutan tropis dan subtropis', 'Paru-paru', 'Berjalan, berlari, dan terbang tidak jauh'),
(14, 'cockroach', 'Kecoak adalah serangga yang sering ditemukan di area lembab seperti rumah dan tempat-tempat kotor. Mereka memiliki tubuh yang pipih, sayap yang menutupi tubuh saat tidak digunakan, dan kemampuan untuk bertahan hidup dalam kondisi yang keras.', 'Kecoa (Blattodea)', 'Insecta (serangga)', 'Omnivora (pemakan segalanya)', 'Sisa makanan manusia dan hewan peliharaan, sampah, tanaman mati dan bahkan bangkai hewan', 'Ovipar (bertelur)', 'Tubuh yang pipih, sayap yang menutupi tubuh saat tidak digunakan', 'Pergerakan yang cepat lincah, bisa terbang dan mampu bertahan hidup dalam kondisi lingkungan ekstrim', 'Tempat yang gelap, lembab, dan tertutup, seperti celah-celah sempit, retakan dinding, balik daun, atau tempat-tempat yang kotor seperti saluran pembuangan, tong sampah, dapur, dan kamar mandi', 'Trakea', 'Merayap dan terbang'),
(15, 'cow', 'Sapi adalah hewan ternak yang penting dalam industri peternakan. Sapi memiliki tubuh yang besar, empat kaki, dan tanduk pada beberapa jenisnya. Sapi adalah hewan herbivora yang dikenal sebagai penghasil daging, susu, dan bahan lainnya. Habitat asli sapi adalah padang rumput dan mereka memakan berbagai jenis rumput, jerami dan daun.', 'Sapi (Bos taurus)', 'Mamalia (menyusui)', 'Herbivora (pemakan tumbuhan)', 'Rumput, jerami, biji-bijian, jagung, dan daun', 'Vivipar (melahirkan)', 'Tubuh yang besar, empat kaki, dan tanduk pada beberapa jenisnya', 'Menghasilkan susu dan daging', 'Padang rumput', 'Paru-paru', 'Berjalan'),
(16, 'crab', 'Kepiting adalah hewan laut yang memiliki tubuh yang dilindungi oleh cangkang keras. Mereka memiliki sepasang capit yang kuat yang digunakan untuk melindungi diri mereka sendiri dan mencari makanan seperti tumbuhan air, kerang, hewan air kecil lainnya bahkan bangkai ikan di dasar perairan. Kepiting terdapat di semua samudra dunia mulai dari kepiting air tawar dan darat, khususnya di wilayah-wilayah tropis. Kepiting juga dijadikan konsumsi oleh manusia karena memiliki rasa yang luar biasa.', 'Kepiting (Brachyura)', 'Arthropoda (beruas-ruas)', 'Omnivora (pemakan segalanya)', 'tumbuhan air, kerang, hewan air kecil bahkan bangkai ikan', 'Ovipar (bertelur)', 'Tubuh yang dilindungi oleh cangkang keras', 'Sepasang capit yang kuat, mampu mengubur dirinya ke dalam tanah', 'Semua wilayah perairan dunia mulai dari laut, sungai, danau', 'Insang', 'Berjalan secara horizontal atau ke kanan kiri saja'),
(17, 'crocodile', 'Buaya adalah reptil besar yang hidup di air tawar, banyak dijumpai di sungai, danau dan rawa-rawa. Buaya memiliki tubuh yang dilapisi kulit bersisik, mulut yang lebar dengan gigi yang tajam, dan ekor yang panjang. Buaya adalah predator yang kuat dan cenderung berburu mangsa di dekat air. Buaya umumnya akan memakan hewan yang lewat di depannya, seperti mamalia kecil, burung, ikan, serangga, katak, dan spesies reptil lainnya', 'Buaya (Crocodylidae)', 'Reptil (melata)', 'Karnivora (pemakan daging)', 'Mamalia kecil, burung, ikan, serangga, katak, spesies reptil lainnya, dan krustasea.', 'Ovipar (Bertelur)', 'Tubuh dilapisi kulit bersisik, mulut lebar dengan gigi tajam, dan ekor yang panjang', 'Membaur dengan lumpur, menyelam cukup lama', 'Wilayah perairan seperti sungai, danau, dan rawa', 'Paru-paru', 'Berjalan, berenang, dan menyelam'),
(18, 'deer', 'Rusa adalah mamalia yang umum ditemukan di berbagai habitat hutan dan padang rumput di seluruh dunia. Mereka memiliki tubuh yang ramping, kaki yang panjang, dan tanduk pada rusa jantan. Rusa adalah herbivora yang memakan rumput, daun, buah-buahan dan sering hidup berkelompok.', 'Rusa (Cervidae)', 'Mamalia (menyusui)', 'Herbivora (pemakan tumbuhan)', 'Rumput, semak kecil, dan daun', 'Vivipar (melahirkan)', 'Memiliki dua kuku besar dan dua kuku kecil di setiap kakinya serta rusa jantan memiliki tanduk', 'Indra penciuman yang mampu menangkap bau dari predator dari jarak jauh', 'Hutan dan padang rumput di seluruh dunia', 'Paru-paru', 'Berlari dengan kecepatan 60-80 km/jam'),
(19, 'dog', 'Anjing adalah hewan peliharaan yang sangat populer dan dekat dengan manusia. Mereka datang dalam berbagai ras dengan ukuran, bentuk, dan kepribadian yang berbeda. Anjing bersifat sosial, cerdas, dan sering digunakan dalam berbagai pekerjaan seperti penjaga. Habitat anjing beragam mulai dari padang savana, perumahan, lereng gunung sehingga makanannya berupa daging dari hewan lain yang juga hidup di habitat itu.', 'Anjing (Canis lupus familiaris)', 'Mamalia (menyusui)', 'Karnivora (pemakan daging)', 'Daging hewan lain', 'Vivipar (melahirkan)', 'Tubuh berukuran sedang, kaki dan ekor tergantung dari jenisnya', 'Menggonggong dan memiliki indera yang kuat', 'Padang savana, perumahan, pekarangan, dan lereng gunung', 'Paru-paru', 'Berlari, memanjat, dan berjalan'),
(20, 'dolphin', 'Lumba-lumba adalah mamalia laut yang hidup di perairan hangat hampir di semua lautan. Mereka memiliki tubuh yang aerodinamis, sirip yang kuat, dan kemampuan untuk berenang dengan cepat. Lumba-lumba juga dikenal sangat cerdas dan sering berinteraksi dengan manusia. Mereka memiliki kemampuan ekolokasi untuk memberi tahu bentuk, ukuran, kecepatan, jarak, dan lokasi objek berdasarkan pantulan suara. Mamalia laut ini sering berkelompok dalam membuat cincin lumpur untuk menjebak ikan, cumi-cumi, dan udang yang akan dimangsa.', 'Lumba-lumba (Stenella longirostris)', 'Pisces (ikan), Mamalia (menyusui)', 'Omnivora (pemakan segalanya)', 'Tumbuhan laut, ikan, cumi-cumi, dan udang ', 'Vivipar (melahirkan)', 'Tubuh yang aerodinamis, sirip yang kuat, dan kemampuan untuk berenang dengan cepat', 'Kemampuan ekolokasi untuk memberi tahu bentuk, ukuran, kecepatan, jarak, dan lokasi objek berdasarkan pantulan suara', 'Perairan hangat hampir di semua lautan', 'Paru-paru', 'Berenang dan menyelam'),
(21, 'dragonfly', 'Capung adalah serangga dengan sayap transparan dan tubuh yang panjang dan ramping. Mereka memiliki kemampuan terbang yang lincah dan sering ditemukan di sekitar air tawar. Capung adalah penyerbuk yang penting dalam ekosistem. Capung akan memakan hama tanaman seperti kutu daun dan nyamuk.', 'Capung (Anisoptera)', 'Insecta (serangga)', 'Omnivora (pemakan segalanya)', 'Hama tanaman seperti kutu daun dan nyamuk', 'Ovipar (bertelur)', 'Serangga dengan sayap transparan dan tubuh yang panjang dan ramping', 'Kemampuan terbang yang lincah', 'Sekitar perairan seperti sawah, danau, sungai, rawa, dan kolam', 'Trakea', 'Terbang'),
(22, 'duck', 'Bebek adalah unggas air yang memiliki paruh lebar dan kaki yang pendek. Mereka sering ditemukan di danau, sungai, dan daerah berair lainnya di seluruh belahan bumi. Bebek adalah hewan yang bermigrasi dan memiliki berbagai spesies dengan warna dan pola bulu yang berbeda. Bebek juga terkenal karena bisa mengapung di atas air dan menyelam ke bawah air untuk mencari makanan seperti tanaman air, ikan, serangga, amfibi kecil, dan cacing.', 'Bebek (Anas domesticus)', 'Aves (burung)', 'Omnivora (pemakan segalanya)', 'Tanaman air, ikan, serangga, amfibi kecil, dan cacing', 'Ovipar (bertelur)', 'Memiliki paruh lebar dan kaki yang pendek, tubuh berbentuk oval, namun kelonjongannya dapat bervariasi tergantung spesiesnya', 'Dapat mengapung diatas air dan memiliki kaki berbentuk selaput', 'Tempat berair atau berlumpur seperti danau, sungai, kolam, dan rawa-rawa', 'Paru-paru', 'Berjalan di darat, mengapung diatas air dan menyelam'),
(23, 'eagle', 'Elang adalah burung pemangsa yang memiliki ukuran besar, sayap yang lebar, dan penglihatan yang tajam. Mereka dikenal dengan kemampuan terbang yang tinggi dan kemampuan berburu mangsa di udara. Burung elang adalah simbol kekuatan dan kebebasan. Elang biasa ditemukan di puncak pegunungan Amerika. Mereka biasa meluncur tepat di atas air, menangkap seekor ikan atau ular dengan kaki mereka.', 'Elang (Nisaetus bartelsi)', 'Aves (burung)', 'Karnivora (pemakan daging)', 'tikus, tupai, kadal, ikan, ular, dan ayam', 'Ovipar (bertelur)', 'berukuran sedang, berbulu, bersayap', 'kaki yang kuat', 'pegunungan, perbukitan, dan dataran tinggi', 'Paru-paru', 'terbang'),
(24, 'echidna', 'Landak adalah mamalia yang memiliki tubuh dengan duri-duri tajam. Mereka memiliki moncong yang panjang dan kaki yang pendek. Landak menggunakan duri mereka sebagai pertahanan terhadap predator. Mereka adalah herbivora dan sering ditemukan di daerah hutan.', 'Landak (Erinaceinae)', 'Mamalia', 'Omnivora', 'daun, serangga, buah', 'melahirkan', 'tubuh membulat dan berduri', 'mengeluarkan duri', 'perkebunan, hutan', 'paru-paru', 'berjalan'),
(25, 'eel', 'Belut adalah ikan yang memiliki tubuh yang panjang, licin, dan tidak berotot. Mereka sering ditemukan di perairan tawar dan payau. Belut memiliki kemampuan untuk menggali lumpur dan tanah basah.', 'Belut (Synbranchidae)', 'Vertebrata', 'Karnivora', 'zooplankton, cacing, kutu air (daphnia/moina), cacing, kecebong, larva ikan, dan larva serangga', 'ovipar (bertelur)', 'panjang dan bulat', 'hidup di lumpur', 'sungai, danau, rawa-rawa dan sawah ', 'kulit tipis pada rongga mulut', 'melatah'),
(26, 'elephant', 'Gajah adalah mamalia terbesar di darat Mereka memiliki tubuh yang besar,belalai yang panjang dan gading yang besar pada gajah jantan.Gajah adalah herbivora dan hidup dalam kelompok sosial yang kompleks. Mereka sangat cerdas dan memiliki ingatan yang kuat', 'Gajah', 'Gajah terdiri dari tiga spesies utama, yaitu gajah Afrika (Loxodonta africana dan Loxodonta cyclotis) serta gajah Asia (Elephas maximus).', 'Herbivora (pemakan tumbuhan', 'Makanan yang umum dikonsumsi oleh gajah meliputi rumput, daun-daunan, bambu, kulit pohon, akar, buah-buahan, dan jerami.', 'Gajah memiliki sistem reproduksi vivipar (melahirkan anak yang telah berkembang sepenuhnya di dalam rahim). Perkawinan terjadi antara seekor jantan dan seekor betina. Masa kehamilan pada gajah berlangsung sekitar 22 bulan.', 'Gajah memiliki tubuh yang besar dan kuat. Mereka memiliki dua taring yang dikenal sebagai gading yang merupakan perpanjangan gigi mereka. Gajah juga memiliki telinga yang besar dan lebar yang mirip dengan benua Afrika, sedangkan telinga gajah Asia lebih kecil dan berbentuk seperti benua India.', 'Gajah dikenal memiliki kecerdasan yang tinggi dan daya ingat yang baik. Mereka juga mampu berkomunikasi menggunakan suara, gerakan tubuh, dan getaran melalui tanah. Gajah juga memiliki kemampuan menggunakan belalainya untuk mengangkat benda-benda berat dan makanan.', 'Gajah Afrika umumnya hidup di sabana, hutan, dan daerah bersemak di Afrika Sub-Sahara. Gajah Asia biasanya ditemukan di hutan-hutan tropis, hutan rawa, dan padang rumput di Asia Selatan dan Tenggara.', 'Gajah bernapas menggunakan paru-paru, seperti mamalia lainnya. Mereka menghirup udara melalui hidung mereka.', 'Gajah memiliki empat kaki yang kuat dan besar, yang memungkinkan mereka berjalan dengan langkah yang panjang dan lambat. Gajah juga bisa berlari dengan kecepatan yang lumayan meskipun tidak secepat hewan-hewan lain. Mereka juga bisa berenang dengan baik menggunakan belalai mereka sebagai snorkel.'),
(27, 'flamingo', 'Flamingo adalah burung dengan leher panjang dan bulu yang cerah. Mereka sering ditemukan di rawa-rawa dan danau dangkal. Flamingo adalah burung yang unik dengan kemampuan untuk berdiri dengan satu kaki dan menggunakan paruhnya yang melengkung untuk menyaring makanan.', 'Flamingo', 'Burung (aves) air yang termasuk dalam famili Phoenicopteridae.', 'Omnivora (pemakan segala)', 'Hewan pemakan filter. Mereka memakan plankton, alga, udang kecil, krustasea, dan invertebrata air lainnya.', 'Ovipar (bertelur). Flamingo adalah hewan monogami yang biasanya membentuk pasangan seumur hidup. Mereka biasanya berkumpul dalam koloni besar untuk berkembang biak. Betina akan bertelur di sarang berbentuk cawan yang mereka bangun dari lumpur dan tanah. Setelah bertelur, kedua induk akan bergantian mengerami telur tersebut.', 'Flamingo memiliki leher panjang dan kaki yang juga panjang. Tubuh mereka diliputi bulu berwarna merah muda hingga oranye kemerahan. Mereka memiliki paruh yang panjang dan melengkung dengan sisir kecil di bagian dalamnya.', 'Salah satu kemampuan khusus flamingo adalah kemampuan mereka untuk berdiri dan berjalan di perairan dangkal menggunakan kaki panjang mereka. Mereka juga bisa terbang dengan kecepatan tinggi dan melakukan penerbangan jarak jauh.', 'Danau, laguna, dan rawa-rawa. Mereka tersebar di berbagai wilayah di seluruh dunia, termasuk Amerika, Eropa, Afrika, dan Asia.', 'Bernapas dengan paru-paru menggunakan proses pernapasan avian yang melibatkan pengambilan udara melalui saluran pernapasan dan pertukaran oksigen dan karbon dioksida di dalam paru-paru.', 'Flamingo menggunakan kakinya yang panjang dan kuat untuk bergerak di perairan dangkal dan berjalan di atas lumpur. Ketika berada di air, mereka berenang dengan menggunakan kaki mereka yang gesit dan berenang dengan leher yang ditekuk ke belakang.'),
(28, 'fly', 'Lalat adalah serangga kecil yang terbang dengan sayap transparan. Mereka sering ditemukan di sekitar sumber makanan yang membusuk. Lalat memiliki siklus hidup yang pendek dan dapat menjadi hama di rumah dan peternakan.', 'Lalat (ord. Diptera)', 'Insecta (Serangga)', 'Omnivora (pemakan segala)', 'Lalat adalah pemakan detritus (makanan yang membusuk), namun beberapa spesies juga bisa menjadi parasit pada hewan lain atau memangsa serangga kecil. Beberapa spesies lalat juga bisa memakan nektar, serbuk sari, atau cairan tumbuhan lainnya.', 'Ovovivipar. Lalat melalui siklus hidup yang melibatkan metamorfosis sempurna. Betina meletakkan telur-telur di substrat yang cocok, seperti kotoran hewan atau bahan organik membusuk. Dari telur tersebut, menetaslah larva (biasa disebut ulat), yang kemudian mengalami beberapa tahap perkembangan sebelum berubah menjadi pupa. Dalam pupa, lalat mengalami metamorfosis hingga akhirnya menjadi dewasa. Setelah keluar dari pupa, lalat dewasa siap untuk berkembang biak.', 'Lalat memiliki tubuh yang kecil dan ramping, terdiri dari kepala, thorax, dan abdomen. Mereka memiliki satu pasang sayap yang berkembang dengan baik, dan juga memiliki tiga pasang kaki yang digunakan untuk bergerak dan menempel pada permukaan.', 'Lalat memiliki beberapa kemampuan khusus yang memungkinkan mereka untuk bertahan hidup dan beradaptasi. Salah satu kemampuan khusus lalat adalah kemampuan mereka dalam terbang dengan cepat dan wendy. Beberapa spesies lalat juga memiliki kemampuan untuk menyebabkan penyakit karena mereka bisa bertindak sebagai vektor penyakit, seperti lalat rumah yang dapat menyebarkan penyakit melalui kontak dengan makanan atau benda-benda lainnya.', 'Lalat dapat ditemukan di berbagai habitat, mulai dari lingkungan perkotaan hingga pedesaan, dan dari daerah tropis hingga daerah beriklim sedang. Mereka cenderung berkumpul di tempat-tempat dengan bahan organik yang membusuk, seperti tempat pembuangan sampah, kotoran hewan, atau tempat-tempat dengan sumber makanan yang melimpah.', 'Lalat bernapas dengan menggunakan sistem trakea. Mereka memiliki saluran udara yang disebut trakea yang terhubung langsung ke permukaan tubuh mereka, memungkinkan pertukaran gas dengan lingkungan.', 'alat memiliki kemampuan terbang yang baik dan sering ditemui dalam kegiatan terbang di sekitar daerah mereka. Mereka menggunakan sayap mereka yang fleksibel untuk bergerak dengan cepat dan lincah di udara. Ketika tidak terbang, lalat berjalan atau merangkak menggunakan kaki mereka di permukaan yang mereka tempati. Beberapa spesies lalat juga bisa melompat dengan jarak yang cukup jauh.'),
(29, 'fox', 'Rubah adalah mamalia yang dikenal karena bulunya yang tebal dan ekornya yang panjang. Mereka beradaptasi dengan baik dan sering ditemukan di berbagai habitat di seluruh dunia. Rubah adalah predator yang pintar dan sering berburu di malam hari.', 'Rubah (Vulpes)', 'Rubah merupakan anggota famili Canidae dan terdapat banyak jenis rubah di seluruh dunia, termasuk Rubah merah (Vulpes vulpes), Rubah arctic (Vulpes lagopus), Rubah fennec (Vulpes zerda), dan banyak lagi.', 'Rubah adalah hewan karnivora, meskipun beberapa jenis juga memakan tumbuhan.', 'Rubah umumnya memangsa hewan kecil seperti tikus, kelinci, burung, serangga, dan reptil. Namun, diet rubah dapat bervariasi tergantung pada spesies dan habitatnya.', 'Rubah adalah hewan ovipar (bertelur) dan memiliki sistem reproduksi internal. Masa kawin rubah terjadi pada musim semi. Setelah kawin, betina rubah akan membuat sarang di dalam tanah atau di bawah semak-semak untuk melahirkan anaknya. Masa kehamilan rubah berlangsung sekitar 50-60 hari dan betina bisa melahirkan 4-5 anak rubah dalam satu kelahiran.', 'Rubah memiliki tubuh yang ramping dan lincah. Mereka memiliki ekor panjang dan bulu tebal yang dapat bervariasi warnanya tergantung pada spesiesnya. Rubah juga memiliki telinga yang tajam dan hidung panjang yang membantu mereka dalam mendengar dan mencium mangsa.', 'Rubah dikenal memiliki kecerdasan yang tinggi dan kemampuan beradaptasi yang baik. Mereka juga memiliki pendengaran yang tajam dan indera penciuman yang sensitif. Beberapa jenis rubah juga memiliki kemampuan menggali lubang dan terowongan di tanah untuk mencari makanan atau membuat sarang.', 'Rubah dapat ditemukan di berbagai habitat di seluruh dunia, termasuk hutan, padang rumput, gurun, tundra, dan daerah perkotaan. Mereka memiliki kemampuan beradaptasi yang baik terhadap berbagai lingkungan.', 'Rubah bernapas melalui paru-paru, sama seperti mamalia lainnya. Mereka mengambil oksigen dari udara melalui hidung dan membuang karbon dioksida melalui proses pernapasan.', 'Rubah adalah hewan yang lincah dan bergerak dengan cepat. Mereka menggunakan kaki mereka yang kuat untuk berlari dan melompat saat mencari mangsa. Selain itu, rubah juga bisa berenang dengan baik dan beberapa spesies rubah memiliki kemampuan memanjat pohon.'),
(30, 'frog', 'Katak adalah amfibi yang hidup di air dan darat. Mereka memiliki kulit yang halus, cakar di jari-jari kaki, dan kemampuan melompat yang baik. Katak mengalami metamorfosis dari tahap katak kecil (kodok) menjadi katak dewasa.', 'Katak', 'Amphibi.', 'Karnivora.', 'Pemakan serangga seperti lalat, jangkrik, capung, dan serangga lainnya.', 'Ovipar melibatkan perubahan metamorfosis.', 'Katak memiliki tubuh yang umumnya berbentuk memanjang dan lebar dengan empat kaki pendek serta kulit yang lembap. Mereka juga memiliki mata yang besar dan bisa memutar ke segala arah.', 'Katak memiliki kemampuan melompat yang sangat baik. Beberapa spesies katak juga memiliki kemampuan mengubah warna kulit mereka untuk menyamarkan diri atau menunjukkan perubahan emosi.', 'Katak ditemukan di seluruh dunia kecuali di daerah kutub. Mereka hidup di berbagai habitat, seperti rawa, kolam, sungai, hutan, dan padang rumput.', 'Kulit dan Paru-paru.', 'Melompat ketika di darat dan berenang ketika di air.'),
(31, 'giraffe', 'Jerapah adalah mamalia yang memiliki leher yang sangat panjang dan kaki yang tinggi. Mereka dikenal dengan tinggi badannya yang mencapai beberapa meter. Jerapah memiliki lidah yang panjang dan biasanya hidup di padang rumput atau sabana. Prosedur kawin terjadi ketika pejantan mengikuti betina yang diinginkannya dan memamerkan perilaku khas, seperti menendang, menyalatkan kepala, atau melawan dengan lehernya. Setelah betina hamil selama sekitar 15 bulan, dia akan melahirkan seekor anak jerapah tunggal.', 'Jerapah (Giraffa camelopardalis)', 'Mamalia', 'Herbivora', 'Tumbuhan, terutama daun, pucuk, ranting, dan buah-buahan.', 'Vivipar (melahirkan anak hidup).', 'Tubuh yang tinggi, ramping, leher panjang, kaki panjang dan kuat, ekor yang relatif pendek, bagian atas tubuh ditutupi oleh bulu-bulu kemerahan dengan bercak-bercak cokelat yang khas.', ' Leher panjang, lidah yang panjang dan fleksibel.', 'Padang rumput, sabana, hutan, dan daerah semak di Afrika. Tersebar di beberapa negara di Afrika, termasuk Kenya, Tanzania, Botswana, dan Afrika Selatan.', 'Paru-paru.', 'Berjalan menggunakan kaki yang panjang.'),
(32, 'goldfish', 'Ikan mas adalah ikan air tawar yang populer sebagai ikan hias. Ikan ini memiliki tubuh yang ramping dengan warna-warna cerah. Ikan mas sering dipelihara di akuarium dan kolam.', 'Ikan mas (Cyprinus carpio)', 'Pisces (vertebrata)', 'Omnivora (memakan tumbuhan dan hewan kecil)', 'Serangga, cacing, krustasea kecil, plankton, biji-bijian, alga, dan dedaunan.', 'Ovipar (bertelur)', 'Silinder, ramping, sirip dorsal (punggung), sirip anal (perut), dan sirip ekor.', 'Mengubah warna kulitnya sesuai dengan lingkungan sekitarnya dan memiliki indera penciuman yang baik.', 'Perairan tawar seperti danau, sungai, dan kolam.', 'Insang', 'Berenang'),
(33, 'goose', 'Angsa adalah burung air yang memiliki leher panjang dan sayap yang kuat. Mereka sering ditemukan di danau dan sungai. Angsa dikenal karena migrasi mereka yang panjang dan membentuk kelompok sosial yang terorganisir. Angsa adalah hewan yang berkembang biak secara seksual. Pada musim kawin, pasangan angsa membentuk ikatan kuat dan monogami. Betina akan membuat sarang dari rumput dan bulu untuk bertelur. Betina biasanya bertelur sekitar 4-7 butir telur dan mengerami selama sekitar 25-30 hari. Setelah menetas, anak angsa atau anakan akan menjadi mandiri dalam beberapa jam dan mereka diasuh oleh kedua orang tuanya.', 'Angsa (Cygnus sp.)', 'Aves genus Cygnus famili Anatidae', 'Herbivora', 'Tanaman dan vegetasi air, seperti rumput, daun, batang, biji-bijian, dan akar-akaran.', 'Ovipar', 'Tubuh yang besar dengan leher panjang, bulu tebal berwarna putih atau abu-abu, paruh yang kuat.', 'Terbang dalam formasi jajar, berenang dengan baik, dan memanfaatkan air sebagai sumber makanan.', 'Habitat air tawar, seperti danau, sungai, rawa-rawa, dan sawah. Beberapa spesies angsa juga dapat ditemukan di habitat pesisir dan laut saat musim migrasi.', 'Paru-paru', 'Berjalan dengan kaki, berenang di air dengan bantuan kaki dan sayap, terbang dengan sayap.'),
(34, 'gorilla', 'Gorila adalah primata terbesar dan termasuk dalam keluarga Hominidae.. Mereka memiliki tubuh yang besar, lengan yang kuat, dan hidup di hutan hujan Afrika. Gorila adalah hewan herbivora yang hidup dalam kelompok yang dipimpin oleh jantan dominan. Gorila memiliki sistem reproduksi vivipar, di mana betina hamil dan melahirkan anaknya. Masa kehamilan gorila berlangsung sekitar 8,5 bulan hingga 9 bulan.', 'Gorila', 'Mamalia.', 'Herbivora.', 'Daun-daunan, buah-buahan, batang pohon, kulit kayu, dan serangga kecil.', 'Vivipar.', 'Tubuh besar dan berotot, lengan yang panjang, dada lebar, kepala yang besar, gigi taring yang besar dan kuat.', 'Kekuatan fisik yang luar biasa, membungkuk, merentangkan otot-otot tubuh mereka, dan menggunakan lengan mereka untuk berayun dari pohon ke pohon, kecerdasan sosial yang tinggi dan dapat menggunakan alat-alat sederhana.', 'Hutan hujan Afrika, terutama di kawasan hutan Kongo, Uganda, dan Rwanda. Mendiami daerah pegunungan yang tinggi.', 'Paru-paru.', 'Empat kaki untuk berjalan, merayap atau merangkak di tanah.'),
(35, 'grasshopper', 'Belalang adalah serangga yang memiliki kemampuan untuk melompat jauh menggunakan kaki belakangnya yang panjang. Mereka sering ditemukan di daerah berumput dan dapat menghasilkan suara yang unik dengan menggosok-gosokkan sayapnya.', 'Belalang', 'Ordo Orthoptera dalam kelas Insecta.', 'Herbivora.', 'Rumput, dedaunan, bunga, dan bagian-bagian tanaman lainnya.', 'Ovipar.', 'Tubuh yang panjang dan ramping, dengan tiga pasang kaki dan sepasang sayap yang seringkali transparan atau berwarna cerah, antena panjang yang berfungsi sebagai organ peraba dan pendengaran.', 'Kemampuan melompat yang hebat, beradaptasi dengan warna sekitar mereka untuk melindungi diri dari pemangsa.', 'Padang rumput, hutan, dan wilayah semi-gurun. Dekat sumber air, seperti sungai atau danau, karena tumbuhan yang menjadi makanan mereka banyak tumbuh di daerah tersebut.', 'Trakea.', 'Melompat, berjalan, berlari.'),
(36, 'hamster', 'Hamster adalah hewan pengerat yang populer sebagai hewan peliharaan. Mereka memiliki tubuh yang kecil, telinga yang pendek, dan pipi yang membesar untuk menyimpan makanan. Hamster aktif di malam hari dan cenderung aktif di malam hari.', 'Hamster', 'Mamalia, keluarga Cricetidae, ordo Rodentia.', 'Herbivora.', 'Biji-bijian seperti biji bunga matahari, biji gandum, biji jagung, biji wijen, kacang-kacangan, sayuran seperti wortel, brokoli, dan seledri.', 'Vivipar.', 'Tubuh kecil dan bulat dengan panjang sekitar 10-15 cm, ekor pendek, kepala bulat, telinga kecil, gigi taring yang terus tumbuh.', 'Menyimpan makanan dalam kantung pipi mereka yang besar, berlari dengan cepat dan melompat pendek. Beberapa spesies hamster dapat berenang dengan baik.', 'Daerah yang bersemak dan gurun di Eurasia dan Afrika Utara. Mereka biasanya hidup di dalam gua atau lubang yang mereka gali di tanah.', 'Paru-paru', 'Kaki yang pendek untuk berjalan, berlari, memanjat, dan melompat.'),
(37, 'harborseal', 'Anjing laut pelabuhan adalah mamalia laut yang hidup di perairan dingin di belahan bumi utara. Mereka memiliki tubuh yang ramping, sirip depan yang kuat, dan kemampuan untuk berenang dengan cepat. Anjing laut pelabuhan sering ditemukan di sekitar pantai d', 'Anjing Laut', 'Mamalia air, keluarga Otariidae.', 'Karnivora (pemakan daging).', 'Ikan, cumi-cumi, kerang, dan krustasea lainnya.', 'Vivipar.', 'Tubuh ramping dan aerodinamis, ekor lebar dan memanjang, sirip depan dan belakang yang kuat.', 'Berenang yang luar biasa, mampu menyelam ke dalam air dalam waktu yang lama, mampu melompat keluar dari air dengan kemampuan yang cukup tinggi.', 'Perairan dingin, termasuk Samudra Pasifik Utara dan Selatan, Samudra Atlantik Utara, dan Lautan Arktik. Tinggal di pantai, pulau-pulau kecil, dan es laut, terutama di sekitar garis pantai yang berbatu.', 'Paru-paru.', 'Berenang degan sirip, merangkak dan berjalan dengan bantuan perut.'),
(38, 'hedgehog', 'Landak adalah mamalia kecil yang memiliki tubuh dengan duri-duri tajam. Mereka menggulung diri mereka menjadi bola ketika merasa terancam. Landak aktif di malam hari dan hidup di berbagai habitat seperti hutan dan padang rumput.', 'Landak', 'Mamalia.', 'Herbivora (makan tumbuhan).', 'Berbagai jenis tumbuhan, termasuk rumput, buah-buahan, akar, batang, dan biji-bijian.', 'Vivipar.', 'Tubuh berbentuk bulat dan dilapisi oleh duri-duri tajam yang disebut \"bulu\" atau \"landak\", moncong pendek, kaki pendek, dan ekor yang lebat.', 'Menggulungkan tubuh mereka menjadi bola yang dilindungi oleh duri-duri tajam saat mereka merasa terancam. Duri-duri tersebut memberikan perlindungan dari predator.', 'Hutan, padang rumput, dan daerah semak. Mereka biasanya tinggal di daerah yang memiliki vegetasi yang cukup untuk dijadikan makanan dan perlindungan.', 'Paru-paru.', 'Berjalan.'),
(39, 'hippopotamus', 'Kuda nil adalah mamalia air terbesar di dunia. Mereka memiliki tubuh yang besar, mulut yang lebar, dan hidung yang menonjol. Kuda nil hidup di danau dan sungai di Afrika dan dikenal menghabiskan sebagian besar waktunya di dalam air. Kuda nil memiliki sistem reproduksi vivipar, di mana betina melahirkan anaknya. Setelah masa kehamilan sekitar 8 bulan, betina melahirkan seekor anak kuda nil. Biasanya, hanya satu anak yang lahir pada satu waktu.', 'Kuda Nil (Hippopotamus amphibius)', 'Mamalia.', 'Herbivora (pemakan tumbuhan).', 'Tanaman air, daun, dan buah-buahan.', 'Vivipar.', 'Tubuh besar dan berat, kepala besar dengan mulut yang luas, gigi taring yang tajam, kulit yang tebal tubuhnya ditutupi oleh rambut kasar yang jarang, dan mereka memiliki ekor pendek.', 'Berenang dengan baik, dapat menutup lubang hidung dan telinga mereka saat berada di dalam air, memiliki kulit yang tebal untuk melindungi diri mereka dari sinar matahari dan cedera saat berkelahi dengan sesama kuda nil.', 'Daerah Afrika sub-Sahara. Biasanya hidup di dekat sungai, danau, atau rawa-rawa, yang menyediakan air yang cukup untuk berenang dan makanan yang melimpah.', 'Paru-paru.', 'Bergerak dengan cepat di darat dengan kaki yang pendek dan gemuk, terampil berenang.'),
(40, 'horse', 'Kuda adalah mamalia besar yang telah dijinakkan oleh manusia selama ribuan tahun. Mereka memiliki tubuh yang kuat, kaki yang panjang, dan ekor yang lebat. Kuda digunakan untuk berbagai aktivitas manusia seperti transportasi, pertanian, dan olahraga.', 'Kuda (Equus ferus caballus)', 'Mamalia.', 'Herbivora (hewan pemakan tumbuhan).', 'Rumput, daun, batang tumbuhan, biji-bijian seperti oat, jagung, dan jelai.', 'Vivipar.', 'Tubuh besar dengan empat kaki yang kuat, leher yang panjang dan kepalanya dilengkapi dengan mulut dan gigi yang cocok untuk mengunyah makanan tanaman, rambut kasar dan ekor yang panjang.', 'Berlari dengan cepat, menyesuaikan diri dengan berbagai medan, daya penglihatan yang baik, dan pendengaran yang tajam.', 'Tersebar di seluruh dunia. Kuda liar biasanya ditemukan di padang rumput dan daerah bersemak di berbagai negara.', 'Paru-paru.', 'Berjalan, berlari, dan melompat dengan empat kaki.'),
(41, 'hyena', 'Hyena adalah mamalia yang dikenal dengan suara tawanya yang khas. Mereka memiliki tubuh yang ramping, kepala yang besar, dan gigi yang kuat. Hyena merupakan hewan predator yang hidup berkelompok dan biasanya berburu mangsa di malam hari.', 'Hyena', 'Mamalia, famili Hyaenidae.', 'Karnivora (pemakan daging)', 'Mamalia kecil hingga besar, reptil, burung, serangga, bangkai, dan sisa-sisa makanan yang ditemukan di sekitar mereka.', 'Vivipar (melahirkan anak yang telah berkembang dalam rahim).', 'Tubuh besar dan berotot dengan kaki-kaki yang kuat, leher yang panjang, kepala besar dengan rahang yang kuat, dan telinga yang besar.', 'Pendengaran yang sangat baik, kemampuan penciuman yang tajam, suara khas yang dapat mereka hasilkan, termasuk tawa yang terkenal, kemampuan lari yang cepat dan bisa mencapai kecepatan hingga 60 kilometer per jam.', 'Padang rumput, savana, hingga hutan, banyak terdapat di Afrika dan beberapa spesies juga dapat ditemukan di bagian tertentu di Asia.', 'Paru-paru.', 'Bergerak dengan empat kaki.'),
(42, 'iguana', 'Iguana adalah reptil yang memiliki tubuh besar, ekor panjang, dan sisik kasar. Mereka sering ditemukan di daerah tropis dan gurun. Iguana adalah herbivora yang hidup di pepohonan dan memiliki kemampuan berjemur untuk mengatur suhu tubuhnya.', 'Iguana', 'Reptil dari keluarga Iguanidae.', 'Herbivora.', 'Daun hijau, bunga, buah, dan beberapa spesies bahkan dapat memakan kuncup-kuncup dan batang tanaman.', 'Ovipar.', 'Tubuh ramping dan panjang, dengan kaki yang kuat dan cakar yang tajam, kulit bersisik yang melindungi tubuh mereka dan dapat berubah warna untuk menyesuaikan dengan lingkungan sekitarnya.', 'Memanjat pohon dengan cakar dan kaki yang kuat. Beberapa spesies iguana juga memiliki kemampuan untuk berenang dengan baik dan dapat tinggal di dekat perairan. Iguana juga dikenal memiliki lidah yang panjang dan peka, yang membantu mereka mendeteksi makanan dan mencium aroma di sekitarnya.', 'Hutan hujan tropis, gurun, daerah semi-gurun, atau bahkan di pulau-pulau di lautan.', 'Paru-paru.', 'Merayap, memanjat, dengan kaki dan cakar mereka yang kuat, berenang menggunakan ekor mereka sebagai dayung.'),
(43, 'jaguar', 'Jaguar merupakan spesies kucing besar yang tergolong dalam keluarga Felidae dan ditemukan di Amerika Selatan dan Amerika Tengah. Mereka memiliki tubuh yang ramping, bulu berbintik-bintik, dan kekuatan yang luar biasa. Jaguar adalah predator yang tangguh dan ahli dalam berburu. Jaguar merupakan hewan yang berkembang biak secara seksual. Proses reproduksi dimulai dengan perkawinan antara pejantan dan betina. Setelah perkawinan, betina akan mengandung selama sekitar 90-110 hari sebelum melahirkan anak jaguar yang biasanya berjumlah 1-4 ekor. Mereka membutuhkan lingkungan yang lebat dan beragam untuk mencari makanan serta memiliki cukup ruang untuk berkelana.', 'Jaguar (Panthera onca)', 'Mamalia.', 'Karnivora.', 'Mamalia, reptil, ikan, dan burung.', 'Vivipar.', 'Tubuh kekar dan berotot, kepala besar dengan gigi taring yang kuat dan dapat menembus tulang mangsa, kaki yang pendek dan kuat serta cakar yang tajam untuk memudahkan mereka berburu dan memanjat pohon.', 'Hewan yang lincah dan memiliki kemampuan bergerak dengan cepat, dapat berlari dengan kecepatan hingga 80 kilometer per jam dalam jarak pendek, melompat dengan jarak yang cukup jauh dan memanjat pohon dengan keahlian yang luar biasa.', 'Hutan hujan tropis dan sabana di Amerika Selatan dan Tengah.', 'Paru-paru.', 'Berjalan, berlari, memanjat.'),
(44, 'jellyfish', 'Ubur-ubur adalah hewan laut yang terdiri dari tubuh transparan dan tentakel yang panjang. Mereka tidak memiliki otak atau tulang belakang dan menggunakan tentakelnya untuk menangkap mangsa. Beberapa ubur-ubur dapat menyengat dan beracun bagi manusia.', 'Ubur-Ubur (Scyphozoa)', 'Invertebrata', 'karnivora', 'zooplankton dan ubur-ubur lainnya', 'seksual dan aseksual', 'Memiliki tubuh lunak dan memiliki tentakel yang sangat beracun', 'aliran listrik', 'lautan', 'hewan ubur-ubur bernapas dengan kulitnya', 'berenang'),
(45, 'kangaroo', 'Kanguru adalah mamalia yang dikenal karena kemampuannya untuk melompat jauh menggunakan kaki belakangnya yang kuat. Mereka sering ditemukan di Australia. Kanguru memiliki kantong di perutnya untuk membawa dan merawat anaknya', 'Kanguru (Macropodidae)', 'Mamalia', 'Herbivora', 'rumput dan pohon', 'Melahirkan', 'Kanguru mempunyai dua kaki belakang yang kuat, telapak kakinya yang besar didesain untuk meloncat', 'melompat', 'Papua dan Australia', 'Bernapas dengan Paru-paru', 'Bergerak melompat'),
(46, 'killerwhale', 'Paus Orca, juga dikenal sebagai paus pembunuh, adalah mamalia laut yang merupakan predator utama di laut. Mereka memiliki tubuh besar, sirip punggung yang khas, dan gigi yang tajam. Orca hidup dalam kelompok sosial yang terorganisir dan memiliki keterampi', 'Paus Orca (Orcinus orca)', 'Mamalia Laut', 'Karnivora', 'ikan, burung laut, dan cumi-cumi', 'melahirkan atau vivipar', 'tubuh besar dan ekor horizontal', 'berburu', 'semua samudra lautan', 'Paru-Paru', 'Berenang'),
(47, 'koala', 'Koala adalah mamalia yang terkenal dengan kebiasaannya memakan daun kayu putih. Mereka memiliki tubuh yang kecil, telinga yang panjang, dan cakar yang kuat untuk memanjat pohon. Koala merupakan hewan endemik Australia dan sering dianggap sebagai simbol ne', 'Koala (Phascolarctos cinereus)', 'Mamalia', 'Herbivora', 'daun eukaliptus', 'Melahirkan', 'bertubuh kecil dan memiliki wajah bulat', 'Kemampuan memanjat pohon', 'Australia', 'Bernapas dengan paru-paru', 'Merangkak'),
(48, 'komodo', 'Komodo adalah kadal terbesar di dunia yang ditemukan di Pulau Komodo, Indonesia. Mereka memiliki tubuh yang besar, kulit yang kasar, dan gigi yang kuat. Komodo adalah predator yang terampil dan menggunakan bisa dalam air liurnya untuk menyerang mangsa.', 'Komodo (Varanus komodoensis)', 'Vertebrata', 'Karnivora', 'rusa, kambing, ayam', 'bertelur', 'besar seperti kadal', 'kamuflase', 'pulau komodo Nusa Tenggara Timur', 'saluran kecil dibawah lidah', 'Berjalan dan berlari'),
(49, 'leopard', 'Macan tutul adalah kucing besar yang ditemukan di berbagai habitat di seluruh Afrika dan Asia. Mereka memiliki tubuh yang ramping, bulu berbintik-bintik, serta kecepatan dan keterampilan berburu yang luar biasa.', 'Macan Tutul (Panthera pardus)', 'Mamalia', 'Karnivora', 'kerbau, rusa, sapi', 'Melahirkan', 'tubuh bertotol hitam', 'Kemampuan berlari, berburu', 'Afrika, Asia Tengah, India, dan Tiongkok', 'paru-paru', 'Berlari dan berburu'),
(50, 'lion', 'Singa adalah kucing besar yang dikenal sebagai\"raja hutan\\\". Mereka memiliki tubuh yang besar, jenggot yang mencolok pada jantan, dan kekuatan yang besar. Singa hidup dalam kelompok sosial yang disebut', 'Singa (Panthera leo)', 'Mamalia', 'Karnivora', 'rusa, hyena, kerbau, sapi', 'Melahirkan', 'tubuh besar, berbulu di leher', 'berburu', 'afrika', 'paru-paru', 'Berlari, berjalan'),
(51, 'lionfish', 'Lionfish adalah ikan air asin yang memiliki duri tajam di tubuhnya. Mereka memiliki pola dan warna yang mencolok, dan duri-durinya beracun. Lionfish biasanya ditemukan di perairan tropis dan terumbu karang.', 'Ikan Lepu Ayam (Pterois)', 'pisces', 'Karnivora', 'ikan', 'Bertelur', 'sirip yang panjang dan berduri', 'duri beracun', 'lautan', 'Insang', 'Berenang'),
(52, 'lizard', 'Kadal adalah reptil yang tersebar luas di seluruh dunia. Mereka memiliki tubuh yang panjang, ekor yang meruncing, dan kemampuan untuk meluncurkan ekornya untuk melarikan diri. Kadal memiliki berbagai spesies dan ciri fisik yang berbeda-beda.', 'Kadal (Lacertilia)', 'reptile', 'omnivor', 'serangga seperti nyamuk, belalang, atau larva, cacing, amfibia', 'Ovipar: kebanyak kadal bertelur. Ovovivipar: yaitu telu yang disimpan di dalam betina sampai anak kadal lahir', 'bertubuh kecil, padat, bersisik licin dan berkilau', 'berlari', 'hutan, gurun pasir, padang rumput, kebun, sawah, rawa', 'paru-paru', 'berjalan dan merangkak'),
(53, 'llama', 'llama adalah mamalia asli Amerika Selatan yang termasuk dalam keluarga unta dan unta-unta. Mereka memiliki tubuh yang besar, bulu yang tebal, dan leher yang panjang. Llama sering digunakan sebagai hewan ternak dan transportasi di pegunungan', 'Ilama (Lama glama)', 'Mamalia', 'Herbivora', 'rumput', 'Melahirkan', 'berbuulu dan tinggi', 'Berlari dan berjalan', 'dataran tinggi Andes yang dingin dan kering', 'Bernapas dengan paru-paru', 'Berlari dan berjalan'),
(54, 'monkey', 'Monyet adalah primata yang ditemukan di berbagai belahan dunia. Mereka memiliki tubuh yang lincah, ekor yang panjang, dan kemampuan untuk menggunakan alat. Monyet hidup dalam kelompok sosial dan memiliki keterampilan sosial yang kompleks.', 'Monyet (Macaca fascicularis)', 'Mamalia', 'Omnivora', 'kacang-kacangan, buah-buahan, biji-bijian, telur, serangga, bahkan kadal', 'Melahirkan', 'berbulu dan berekor panjang', 'Melompat ', 'hutan hujan tropika, hutan musim, hutan rawa mangrove sampai hutan montane seperti yang terdapat di Himalaya', 'Bernapas dengan paru-paru', 'Berjalan, berlari, melompat'),
(55, 'mosquito', 'Nyamuk adalah serangga yang dikenal menghisap darah manusia dan hewan lainnya. Nyamuk memiliki tubuh yang kecil, sayap yang transparan, dan belalai yang panjang untuk menghisap darah. Nyamuk adalah vektor penyakit seperti malaria, demam berdarah, dan dema', 'Nyamuk (Culicidae)', 'Insecta', 'karnivora', 'nektar dan darah', 'Bertelur', 'bersayap dan kecil', 'kemampuan untuk terbang dan menghisap', 'tempat yang banyak airnya atau tempat penampungan air, seperti selokan, vas atau pot tanaman, tempat minum hewan peliharaan, kolam renang, atau tempat sampah', 'trakea', 'terbang');
INSERT INTO `animal` (`id_animal`, `nama_hewan`, `description`, `nama`, `jenis`, `diet`, `makanan`, `reproduksi`, `tubuh`, `kemampuan`, `habitat`, `pernapasan`, `pergerakan`) VALUES
(56, 'moth', 'Ngengat adalah serangga dengan sayap lebar dan tubuh berbulu. Mereka umumnya aktif di malam hari dan menarik diri di siang hari. Ngengat sering kali memiliki warna dan pola yang indah pada sayapnya.', 'Ngengat 9Gypsy moth Lymantria dispar)', 'Insecta', 'Omnivora', 'nektar ', 'Bertelur', 'Memiliki tubuh kecil dan bersayap menyerupai kupu-kupu', 'terbang', 'Afrika, Asia, maupun Eropa', 'Trakea', 'terbang'),
(57, 'mouse', 'Tikus adalah hewan pengerat yang dapat ditemukan di seluruh dunia. Mereka memiliki tubuh yang kecil, telinga dan ekor yang panjang, serta gigi yang tumbuh terus menerus. Tikus adalah hewan nokturnal dan sering menjadi hama di rumah atau peternakan.', 'Tikus (Muridae)', 'mamalia', 'Omnivora', 'buah-buahan, sayuran, dan biji-bijian', 'Melahirkan', 'kecil dan berbulu', 'menggali, berenang, melompat dan memanjat pohon ', 'perumahan, sawah dan pasar (tempat kotor)', 'Paru-paru', 'merangkak berlari'),
(58, 'orangutan', 'Orangutan adalah kera besar yang ditemukan di hutan hujan Asia Tenggara. Mereka memiliki tubuh yang besar, lengan yang panjang, dan kepala yang menonjol. Orangutan adalah hewan sosial yang cerdas dan menghabiskan sebagian besar waktunya di atas pohon.', 'Orangutan (Pongo)', 'Mamalia', 'Omnivora', 'Buah-buahan, dedaunan, kulit kayu, bunga, dan serangga', 'Melahirkan', 'Memiliki tubuh menyerupai monyet, tetapi berukuran lebih besar ', 'kemampuan untuk memanjat pohon', 'hutan-hutan tropis, terutama di lembah-lembah sungai', 'Paru-paru', 'Berlari, berjalan, memanjat'),
(59, 'ostrich', 'Burung unta adalah burung besar yang ditemukan di padang rumput dan gurun di Afrika dan Timur Tengah. Mereka memiliki tubuh yang tinggi, leher yang panjang, dan sayap yang besar. Burung unta tidak bisa terbang tetapi memiliki kecepatan lari yang tinggi.', 'Burung Unta (Struthio camelus)', 'aves', 'Omnivora', 'daun, buah, biji-bijian, akar, serangga, hewan kecil', 'Bertelur', 'Memiliki tubuh yang tingga, tidak menyerupai burung dan bulu pada bagian badan yang tebal', 'Berlari dan tidak dapat terbang', 'Afrika Tengah dan Afrika Selatan', 'Trakea', 'Berlari dan berjalan'),
(60, 'otter', 'Berang-berang adalah mamalia air yang ditemukan di perairan tawar di berbagai belahan dunia. Mereka memiliki tubuh yang panjang, bulu yang lebat, dan cakar yang kuat untuk memanjat dan berenang. Berang-berang sangat terampil dalam mencari makanan di dalam', 'Berang-Berang (Lutrinae)', 'Mamalia', 'Karnivora', 'katak, ular, crustacea termasuk kepiting, udang,ikan bahkan mamalia kecil lainnya', 'Melahirkan', 'Memiliki tubuh yang sedang, berbulu dan memiliki kaki yang pendek', 'hidup di dua alam', 'danau, sungai, lahan basah maupun hutan mangrove', 'Bernapas dengan paru-paru', 'Berlari, berenang'),
(61, 'owl', 'Burung hantu adalah burung pemangsa yang dikenal karena matanya yang besar dan kemampuan terbang tanpa suara. Mereka sering ditemukan di hutan dan lingkungan yang gelap. Burung hantu memiliki kemampuan pendengaran yang tajam dan sering aktif di malam hari', 'Burung Hantu (Strigiformes)', 'Vertebrata', 'Karnivora', 'Pemakan daging', 'Bertelur', 'Memiliki tubuh yang sama dengan burung lainnya dan bentuk muka yang bulat dengan paruh yang pendek dan melengkung', 'dapat memutar kepala hampir ke segala arah', 'berbagai daerah terbuka, mulai dari hutan hingga padang rumput', 'paru-paru dan saat terbang dibantu dengan pundi-pundi udara', 'Terbang'),
(62, 'panda', 'Panda adalah mamalia yang dikenal dengan bulunya yang berwarna hitam dan putih. Mereka adalah hewan herbivora yang hidup di pegunungan Cina. Panda adalah hewan yang dilindungi dan sering dianggap sebagai simbol pelestarian spesies.', 'Panda (Ailuropoda melanoleuca)', 'Mamalia', 'Herbivora', 'Bambu', 'Melahirkan', 'Memiliki tubuh yang besar dibalut dengan bulu berwarna hitam dan putih', 'memanjat pohon', 'Dataran China, hutan pada ketinggian di atas 1.500 meter dari permukaan laut dengan banyak pohon bambu', 'Paru-paru', 'Berjalan, merangkak, memanjat'),
(63, 'parrot', 'Burung beo adalah burung yang memiliki kemampuan untuk menirukan suara manusia dan suara-suara lainnya. Mereka memiliki tubuh yang kecil, paruh yang kuat, dan bulu yang cerah. Burung beo adalah burung sosial dan memiliki kemampuan belajar yang luar biasa.', 'Burung Beo (Psittaciformes)', 'Vertebrata', 'Karnivora', 'ulat tepung, larva lalat, cacing lilin, dan ulat', 'Bertelur', 'Memiliki tubuh unik dengan paruh yang bulat dan besar serta memiliki bulu yang berwarna cerah', 'erdas dan pandai meniru suara', 'hutan-hutan basah', 'Trakea', 'Terbang'),
(64, 'peacock', 'Burung merak adalah burung dengan ekor panjang dan bulu yang berwarna-warni. Mereka sering ditemukan di hutan dan hutan hujan di Asia. Burung merak jantan dikenal dengan penampilannya yang spektakuler saat memamerkan ekornya.', 'Burung Merak (Pavo)', 'Vertebrata', 'Omnivora', 'rumput dan biji-bijian serta ular dan kadal kecil juga', 'Bertelur', 'Memiliki tubuh berwarna cerah, jika sudah dewasa memiliki ekor yang besar dan dapat mekar yang indah untuk dipandang', 'Memekarkan ekor melebihi ukuran badannya', 'dataran rendah berupa ekosistem savana dengan ketinggian bertengger 4-25 m', 'Trakea', 'Berjalan dan dapat terbang pendek'),
(65, 'penguin', 'Penguin adalah burung laut yang tidak bisa terbang yang ditemukan di belahan bumi selatan. Mereka memiliki tubuh yang ramping, sayap yang beradaptasi menjadi sirip, dan kemampuan berenang yang baik. Penguin hidup dalam kelompok besar dan biasanya tinggal ', 'Penguin (Spheniscidae)', 'Vertebrata', 'Karnivora', 'Ikan-ikan kecil', 'Bertelur', 'Memiliki tubuh yang pendek dan memiliki warna kontras hitam, putih, biru dan kuning serta kaki yang pendek', 'mampu berenang dengan kecepatan 6 hingga 12 km/jam bahkan pernah tercatat hingga 27 km/jam', 'Kutub Selatan adalah satu satunya tempat penguin ditemukan', 'paru - paru , rongga hidung', 'Berjalan dan berenang'),
(66, 'pig', 'Babi adalah mamalia yang dapat ditemukan di seluruh dunia. Mereka memiliki tubuh yang besar, hidung yang panjang, dan kaki yang pendek. Babi memiliki banyak jenis, seperti babi hutan dan babi ternak, dan sering digunakan sebagai sumber makanan.', 'Babi (Sus)', 'Ungulata', 'Omnivora', 'Daging maupun tumbuh-tumbuhan', 'Melahirkan', 'Memiliki tubuh panjang, muka sedikit cekung dan telinga tegak mengarah ke depan', 'Bisa berenang, memiliki navigator yang baik', 'Hutan', 'Paru-paru', 'Berjalan'),
(67, 'platypus', 'Platipus adalah mamalia kecil yang ditemukan di Australia. Mereka memiliki paruh seperti bebek, kaki berselaput, dan kemampuan untuk bertelur. Platipus sangat unik karena mereka adalah satu-satunya mamalia yang bertelur dan memiliki kelenjar beracun di ka', 'Platipus', 'Vertebrata', 'Karnivora', 'cacing, udang, dan hewan kecil yang hidup di dasar sungai', 'Ovipar (Bertelur)', 'mirip dengan bebek, bentuk badan ramping (streamlined) dan pendek dengan paruh lebar pipih (bill) di bagian depan', 'pendeteksi aliran listrik dan pendeteksi gerakan', 'Australia timur, termasuk Tasmania', 'paru-paru dan nostril', 'gaya berjalan seperti reptil, dengan kaki di sisi tubuh, bukan di bawahnya'),
(68, 'polarbear', 'Beruang Kutub adalah mamalia besar yang ditemukan di daerah Kutub Utara. Mereka memiliki lapisan lemak yang tebal, bulu putih, dan kemampuan berenang yang baik. Beruang kutub bergantung pada es laut untuk makanannya dan sering dikaitkan dengan perubahan i', 'Beruang Kutub (Ursidae)', 'Mamalia', 'Carnivora', 'Buah, kacang-kacangan, ikan, dan hewan ', 'Melahirkan', 'Berbulu tebal, memiliki cakar, bermoncong panjang', 'Dapat berlari mencapai kecepatan 50 km/jam (30 mph)', 'Hutan', 'Paru-paru', 'Berjalan'),
(69, 'rabbit', 'Kelinci adalah mamalia kecil dengan telinga yang panjang dan gigi yang terus tumbuh. Mereka ditemukan di berbagai habitat di seluruh dunia. Kelinci adalah hewan herbivora yang sering dipelihara sebagai hewan peliharaan atau digunakan sebagai sumber makana', 'Kelinci (Lepus)', 'Mamalia', 'Herbivora', 'Sayur dan rumput-rumputan', 'Melahirkan', 'Telinga panjang, kaki bagian belakang yang kuat, mempunyai gigi depan yang panjang', 'Mampu mendeteksi ancaman dari segala arah, karena kemampuan penglihatannya menjangkau 360 derajat', 'Padang rumput', 'Paru-paru', 'Melompat'),
(70, 'raccoon', 'Rakun adalah mamalia yang ditemukan di Amerika Utara dan Amerika Tengah. Mereka memiliki tubuh berukuran kecil hingga sedang, ekor yang halus, dan \\\"topeng\\\" hitam yang khas di sekitar mata. Rakun adalah hewan yang lincah dan sering mencari makan di sekit', 'Rakun (Procyon lotor)', 'Mamalia', 'Omnivora', 'berbagai jenis buah-buahan, sayuran, serangga, ikan, udang, kepiting', 'Melahirkan', 'Kulitnya terdiri dari rambut abu-abu yang tebal untuk mencegah masuknya hawa dingin kedalam tubuh. Hewan ini dikenal karena cakarnya yang sangat tangkas', 'memecahkan masalah dan menyelesaikan tugas yang kompleks dengan cara yang kreatif', 'terletak di hutan gugur dan campuran. Tapi berkat kemampuan adaptasi yang tinggi, mereka dapat kita temukan di daerah pegunungan hingga rawa-rawa', 'Paru-paru', 'Merangkak'),
(71, 'rhinoceros', 'Badak adalah mamalia besar yang dikenal memiliki kulit tebal dan cula di hidungnya. Badak ditemukan di Afrika dan Asia. Badak terancam punah karena perburuan ilegal dan hilangnya habitat.', 'Badak (Rhinocerotidae)', 'Mamalia', 'Herbivora', 'Tumbuhan', 'Melahirkan', 'Memiliki tubuh berukuran besar yang dapat mencapai bobot lebih dari satu ton', 'Mampu berlari dengan kecepatan 48 hingga 64 km/jam', 'Hutan dan rawa', 'Paru-paru', 'Berjalan'),
(72, 'salamander', 'Salamander adalah amfibi yang ditemukan di berbagai belahan dunia. Mereka memiliki tubuh yang panjang, ekor yang meruncing, dan kemampuan untuk meregenerasi anggota tubuh yang hilang. Salamander umumnya hidup di perairan', 'Salamander (Urodela)', 'Amfibi', 'Karnivora', 'serangga, cacing, siput, dan hewan kecil lainnya', 'bertelur-beranak', 'panjang dan ramping, kulit lembap dan halus, serta ekor yang panjang juga memiliki kaki kecil', 'menyembuhkan diri sendiri', 'air tawar dan hutan lembap, terutama di daerah beriklim di belahan bumi utara', 'menggunakan kulitnya untuk bernapas', 'Berenang'),
(73, 'scorpion', 'Kalajengking adalah arakhnida yang memiliki tubuh bersegmen, cakar yang kuat, dan ekor yang mengandung racun. Mereka ditemukan di berbagai habitat di seluruh dunia. Beberapa spesies kalajengking dapat menghasilkan sengatan yang berbahaya bagi manusia. Kalajengking biasanya memakan serangga seperti kecoak dan laba-laba.', 'Kalajengking (Scorpiones)', 'Insecta (serangga), arthropoda (beruas-ruas)', 'Karnivora (pemakan daging)', 'Serangga kecil seperti kecoak dan laba-laba', 'Ovovivipar (bertelur dan melahirkan)', 'Tubuhnya terdiri dari banyak ruas-ruas yang terlindung cangkang tipis, capit yang kuat, dan ekor meruncing.', 'Bersinar dalam gelap, ekor yang mengandung racun', 'Berbagai habitat kering di seluruh dunia', 'Paru-paru', 'Bergerak menggunakan delapan kakinya'),
(74, 'searays', 'Pari Laut adalah ikan laut dengan tubuh pipih dan sirip dada yang berubah menjadi sayap. Mereka ditemukan di perairan tropis dan sering memiliki pola dan warna yang menarik. Pari Laut memiliki kemampuan untuk berenang dengan mengayunkan sayapnya. Mereka menghabiskan sebagian besar waktunya dengan terkubur di dasar laut, bersembunyi dari pemangsa, seperti hiu atau menunggu mangsa seperti kerang, tiram, udang, dan kepiting lewat.', 'Ikan pari (Cheloniidae)', 'Pisces (ikan)', 'Karnivora (pemakan daging)', 'Kerang, tiram, udang, lobster, dan kepiting', 'Ovipar (bertelur)', 'Tubuh pipih dan sirip dada yang berubah menjadi sayap', 'Mampu mengubur dirinya di dasar laut', 'Lautan tropis di seluruh dunia', 'Insang', 'Berenang'),
(75, 'seaturtle', 'Penyu adalah reptil laut yang ditemukan di perairan hangat di seluruh dunia. Mereka memiliki tubuh yang besar, cangkang yang keras, dan kemampuan untuk bernapas di dalam air dan di darat. Penyu hijau menghabiskan sebagian besar hidupnya di bawah air dan meninggalkan air untuk bertelur di pantai. Penyu memakan rumput laut, tanaman air, siput, ikan, udang, dan kepiting.', 'Penyu (Chelonioidea)', 'Reptil (melata)', 'Omnivora (pemakan segalanya)', 'Ikan-ikan kecil, ubur-ubur, rumput laut, tanaman air, siput, ikan, udang, dan kepiting', 'Ovipar (bertelur)', 'Mirip seperti kura-kura, namun kakinya seperti sirip, cangkang yang keras dan kokoh untuk melindungi tubuh penyu', 'Berenang, navigasi, menyelam, dan bertahan hidup di air asin', 'Lautan hangat di seluruh dunia', 'Paru-paru', 'Merayap dan berenang'),
(76, 'seaurchins', 'Bulu babi adalah hewan laut dengan tubuh berduri yang hidup di terumbu karang. Mereka memiliki duri yang beracun dan berfungsi sebagai perlindungan dari predator. Bulu babi terdiri dari berbagai spesies dengan bentuk dan ukuran yang berbeda. Makanan hewan ini adalah ganggang, rumput laut, ikan yang sudah mati, dan kerang.', 'Bulu babi atau landak laut (Echinoidea)', 'Echinodermata (berkulit duri)', 'Omnivora (pemakan segalanya)', 'Ganggang, rumput laut, ikan yang sudah mati, dan kerang', 'Ovipar (bertelur)', 'Tubuh berduri ', 'Duri yang beracun dan berfungsi sebagai perlindungan dari predator', 'Terumbu karang di seluruh pantai dan lautan', 'Kulit', 'Merayap'),
(77, 'shark', 'Hiu adalah ikan predator yang ditemukan di lautan di seluruh dunia. Mereka memiliki tubuh yang ramping, sirip yang besar, dan gigi yang tajam. Hiu adalah hewan yang menakutkan, tetapi penting dalam menjaga keseimbangan ekosistem laut. Mangsa favorit hiu adalah mamalia laut terutama singa laut dan anjing laut. Hiu menggunakan unsur kejutan dan memanfaatkan kemampuan dapat mencium setetes darah dari jarak yang sangat jauh untuk mengejar mangsanya.', 'Ikan Hiu (Selachimorpha)', 'Pisces (ikan)', 'Karnivora (pemakan daging)', 'Ikan dan mamalia laut terutama singa laut dan anjing laut', 'Ovovivipar (bertelur dan melahirkan)', 'Tubuh yang ramping, sirip yang besar, dan gigi yang tajam', 'Mencium setetes darah dari jarak yang sangat jauh', 'Lautan di seluruh dunia', 'Insang', 'Berenang'),
(78, 'sheep', 'Domba adalah hewan ternak yang dikenal dengan bulunya yang lebat dan digunakan untuk mendapatkan wol. Mereka memiliki tubuh yang gemuk, tanduk melingkar, dan merupakan hewan herbivora. Domba sering diternakkan untuk diambil daging, susu, dan wolnya. Habitat asli domba adalah di dataran tinggi seperti pegunungan dan makanannya adalah rumput, daun, dan kacang-kacangan.', 'Domba (Ovis aries)', 'Mamalia (menyusui)', 'Herbivora (pemakan tumbuhan)', 'rumput, daun, buah, dan kacang-kacangan', 'Vivipar (melahirkan)', 'Tubuh yang gemuk, bulunya lebat, tanduk melingkar', 'Menghasilkan wol', 'Habitat asli di dataran tinggi seperti pegunungan ', 'Paru-paru', 'Berjalan dan melompat'),
(79, 'slug', 'Siput adalah moluska yang memiliki tubuh lunak yang dilindungi oleh cangkang. Mereka bergerak perlahan menggunakan kaki perutnya dan sering ditemukan di berbagai habitat, termasuk darat, air tawar, dan laut di seluruh dunia. Makanan hewan ini adalah sayuran dan buah-buahan.', 'Siput (Helix)', 'Mollusca (tubuh lunak)', 'Herbivora (pemakan tumbuhan)', 'Sayuran dan buah-buahan', 'Ovipar (bertelur)', 'Tubuh lunak, kaki di perutnya, beberapa memiliki cangkang', 'Berlindung di dalam cangkang', 'Berbagai habitat termasuk darat, air tawar, dan laut di seluruh dunia', 'Paru-paru', 'Merayap'),
(80, 'snail', 'Keong adalah moluska yang memiliki tubuh lunak yang dilindungi oleh cangkang yang khas. Keong memiliki kaki perut dan ditandai dengan kemampuannya untuk menarik tubuhnya ke dalam cangkang ketika terancam. Keong hidup di berbagai habitat, termasuk di darat, di air dan kebanyakan pantai. Umumnya keong memakan sayuran tetapi juga rumput laut, kacang-kacangan, ikan, maupun udang.', 'Keong (Pila)', 'Invertebrata (tidak bertulang belakang), mollusca (tubuh lunak)', 'Omnivora (pemakan segalanya)', 'Sayuran, rumput laut, kacang-kacangan, ikan, maupun udang', 'Ovipar (bertelur)', 'Memiliki cangkang, tubuh memiliki tiga bagian besar yaitu kepala, kaki dan perut', 'Berlindung di dalam cangkang', 'Berbagai habitat termasuk darat, air dan kebanyakan pantai', 'Paru-paru', 'Merayap'),
(81, 'snake', 'Ular adalah reptil yang dikenal karena tubuhnya yang panjang dan tidak memiliki kaki. Mereka adalah predator yang menggunakan gigi berbisa atau gigi penyempit untuk menangkap dan memangsa mangsanya. Ular memiliki berbagai spesies dengan karakteristik dan hidup di berbagai habitat di seluruh dunia. Sebahai hewan karnivora, mereka memakan berbagai hewan mulai dari unggas, hewan pengerat kecil seperti tikus dan tupai hingga mamalia besar sekalipun.', 'Ular (Serpentes)', 'Reptil (melata)', 'Karnivora (pemakan daging)', 'Unggas, hewan pengerat kecil seperti tikus dan tupai hingga mamalia besar ', 'Ovipar (bertelur) dan ovovivipar (bertelur dan melahirkan)', 'Tubuhnya panjang dan tidak memiliki kaki', 'Melilit dan gigi berbisa atau gigi penyempit untuk menangkap mangsa.', 'Berbagai habitat di seluruh dunia', 'Paru-paru', 'Melata dan merambat'),
(82, 'spider', 'Laba-laba adalah serangga yang dikenal memiliki delapan kaki dan jaring yang rumit. Laba-laba adalah predator yang menangkap mangsa dengan menggunakan jaringnya. Laba-laba memiliki berbagai spesies dengan ukuran dan warna yang beragam.', 'Laba-laba (Araneae)', 'Insecta (serangga), arthropoda (beruas-ruas)', 'Karnivora (pemakan daging)', 'Serangga seperti semut, nyamuk, dan lalat', 'Ovipar (bertelur)', 'Memiliki delapan kaki, tubuh dibagi menjadi dua bagian yaitu depan dan belakang.', 'Membuat jaring, menyuntikkan racun', 'Pohon, di bawah batu, atau pada serasah daun', 'Trakea', 'Merayap'),
(83, 'squirrel', 'Tupai adalah hewan kecil dengan tubuh ramping dan ekor yang panjang. Mereka memiliki cakar yang kuat untuk memanjat dan gigi yang tajam untuk mengunyah makanan. Tupai sering ditemukan di hutan dan taman sebagai hewan liar atau hewan peliharaan di Amerika. Tupai suka mencari makanan seperti kacang, biji, kuncup, dan bunga pohon. Menjelang musim dingin, tupai membawa makanannya dan menguburnya di beberapa lokasi, tetapi terkadang mereka lupa persis di mana. Sehingga benih dan kacang yang terkubur ini bertunas dan tumbuh di musim semi berikutnya.', 'Tupai (Scandentia)', 'Mamalia (menyusui)', 'Omnivora (pemakan segalanya)', 'Kacang, biji, kuncup, bunga pohon, dan kadang serangga', 'Vivipar (melahirkan)', 'Tubuhnya ramping, ekornya panjang, cakar yang kuat, dan gigi yang tajam', 'Membawa banyak makanan dengan mulutnya', 'Hutan dan taman sebagai hewan liar atau hewan peliharaan di Amerika', 'Paru-paru', 'Berjalan, berlari, dan memanjat'),
(84, 'starfish', 'Bintang laut adalah hewan laut yang memiliki tubuh dengan lengan bercabang. Mereka ditemukan di dasar laut di berbagai habitat, dari perairan dangkal hingga perairan dalam. Bintang laut dapat memiliki berbagai warna dan pola yang indah. Sebagian besar bintang laut memiliki kulit berduri dan lima lengan yang ditutupi dengan organ seperti penjepit dan pengisap yang memungkinkan hewan merayap perlahan di sepanjang dasar laut. Makanan favoritnya adalah moluska seperti kerang, tiram, dan siput.', 'Bintang laut (Asteroidea)', 'Echinodermata (berkulit duri)', 'Karnivora (pemakan daging)', 'Moluska seperti kerang, tiram, dan siput', 'Ovovivipar (bertelur dan melahirkan)', 'Kulit berduri dan lima lengan menyerupai bintang', 'Lengan ditutupi dengan organ seperti penjepit dan pengisap ', 'Dasar laut mulai perairan dangkal hingga perairan dalam', 'Kulit', 'Merayap'),
(85, 'swan', 'Angsa adalah burung air yang dikenal dengan warna bulunya yang putih atau hitam polos, lehernya yang panjang dan paruhnya yang lebar. Mereka sering ditemukan di danau, sungai, dan lahan basah lainnya di seluruh belahan bumi. Angsa sering bermigrasi dan hidup dalam kelompok besar. Burung besar ini makan dengan mencelupkan kepalanya ke dalam air untuk memetik tanaman air, akar, dan umbi yang terendam, tetapi mereka juga akan memakan biji-bijian sereal, jagung, dan sejenis kerang.', 'Angsa (Cygnini)', 'Aves (burung)', 'Omnivora (pemakan segalanya)', 'tanaman air, akar, umbi yang terendam, biji-bijian sereal, jagung, dan sejenis kerang', 'Ovipar (bertelur)', 'Warna bulunya putih atau hitam polos, lehernya panjang dan paruhnya lebar.', 'Mencelupkan kepalanya ke dalam air untuk mencari makanan', 'Danau, sungai, dan lahan basah lainnya di seluruh belahan bumi', 'Paru-paru', 'Berjalan dan terbang'),
(86, 'tiger', 'Harimau adalah kucing liar terbesar di dunia yang dikenal sebagai predator yang kuat dan berbahaya. Harimau mudah dikenali dari tubuhnya yang besar, bulunya yang berwarna jingga kemerahan dengan garis-garis gelap serta memiliki gigi dan cakar yang tajam. Harimau hidup di hutan sabana di Asia dan Afrika, mereka biasa menandai pepohonan di wilayahnya dengan urin dan cakaran khusus. Mereka memakan rusa, menikmati air dan dapat berenang dengan baik.', 'Harimau (Panthera tigris)', 'Mamalia (menyusui)', 'Karnivora (pemakan daging)', 'Rusa, babi hutan, dan monyet', 'Vivipar (melahirkan)', 'Tubuhnya besar, bulunya berwarna jingga kemerahan dengan garis-garis gelap, memiliki gigi dan cakar yang tajam', 'Menandai pepohonan di wilayahnya dengan urin dan cakaran khusus', 'Hutan sabana di Asia dan Afrika', 'Paru-paru', 'Berjalan, berlari, dan memanjat'),
(87, 'turtle', 'Kura-kura adalah reptil dengan cangkang keras yang melindungi tubuhnya dan sering kali berumur panjang. Mereka memiliki tubuh yang datar dan ekor yang pendek. Kura-kura hidup di berbagai habitat, termasuk di darat dan air tawar sehingga bisa ditemukan di daerah lembab seperti rawa, sungai, danau di seluruh belahan bumi. Kura-kura tidak hanya memakan sayuran, buah-buahan tetapi juga serangga, cacing, dan ikan.', 'Kura-kura (Testudines)', 'Reptil (melata)', 'Omnivora (pemakan segalanya)', 'Sayuran, buah-buahan, serangga, cacing, dan ikan', 'Ovipar (bertelur)', 'Tubuh datar, cangkang keras dan ekor pendek', 'Mampu bersembunyi di dalam cangkangnya', 'Berbagai habitat termasuk darat dan air, di daerah lembab seperti rawa, sungai, dan danau di seluruh belahan bumi', 'Paru-paru', 'Berjalan dan melata/merayap'),
(88, 'whale', 'Paus adalah mamalia laut terbesar yang pernah ada yang hidup di seluruh lautan. Mereka memiliki tubuh yang besar, sirip punggung dan ekor yang kuat. Paus adalah hewan yang hidup di lautan dan bernapas menggunakan lubang hidung yang disebut \"lubang sembur\". Hewan raksasa ini memakan ikan dan hewan kecil mirip udang yang disebut krill. Mereka sering berenang secara berkelompok atau terkadang juga sendirian.', 'Paus (Cetacea)', 'Mamalia (menyusui)', 'Karnivora (pemakan daging)', 'Ikan dan hewan kecil mirip udang yang disebut krill', 'Vivipar (melahirkan)', 'tubuh yang besar, sirip punggung, dan ekor yang kuat', 'Lubang hidung yang disebut \"lubang sembur\" untuk bernafas dan menyemprotkan air', 'Di seluruh lautan', 'Paru-paru', 'Berenang'),
(89, 'wolf', 'Serigala adalah hewan liar yang masih berkerabat dengan anjing dan bisa ditemui hampir di berbagai hutan di Asia, Eropa, dan Afrika. Mereka memiliki tubuh yang ramping, cakar yang kuat, dan gigi yang tajam. Serigala adalah hewan sosial yang hidup dalam kelompok yang disebut \"kawanan serigala\". Mereka juga memiliki lolongan yang digunakan sebagai cara untuk memanggil serigala lain atau memperingatkan bahaya dan terkadang suka melolong saat bulan purnama. Serigala di alam memakan rusa, kelinci, dan babi hutan.', 'Serigala (Canis lupus)', 'Mamalia (menyusui)', 'Karnivora (pemakan daging)', 'Rusa, kelinci, dan babi hutan', 'Vivipar (melahirkan)', 'Tubuh yang ramping, cakar yang kuat, dan gigi yang tajam', 'Lolongan sebagai cara untuk memanggil serigala lain atau memperingatkan bahaya dan terkadang suka melolong saat bulan purnama', 'Hampir di berbagai hutan di Asia, Eropa, dan Afrika', 'Paru-paru', 'Berjalan, berlari, dan memanjat'),
(90, 'zebra', 'Zebra adalah hewan yang dikenal dengan ciri khas pola belang hitam dan putih pada tubuhnya. Zebra merupakan mamalia herbivora yang hidup di padang rumput dan sering ditemukan di Afrika. Zebra memakan rumput dan hidup dalam kelompok besar serta memiliki kemampuan untuk berlari dengan cepat.', 'Zebra (Equus zebra)', 'Mamalia (menyusui)', 'Herbivora (pemakan tumbuhan)', 'Rumput', 'Vivipar (melahirkan)', 'Berkaki 4, memiliki pola belang hitam dan putih', 'Kecepatan lari ±68,4 km/jam', 'Padang rumput, Afrika', 'Paru-paru', 'Berjalan dan berlari');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `animal`
--
ALTER TABLE `animal`
  ADD PRIMARY KEY (`id_animal`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `animal`
--
ALTER TABLE `animal`
  MODIFY `id_animal` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=91;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
